version: '3.7'
services:
  jenkins:
    build: ./jenkins
    restart: always
    ports:
      - 8081:8080
      - 50000:50000
    container_name: my-jenkins-3
    volumes:
      - ~/jenkins_data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
