---
- hosts: all
  become: yes
  tasks:
  - name: Install dependencies for PostgreSQL
    apt: name={{ item }} update_cache=true state=latest
    with_items:
    - bash
    - openssl
    - libssl-dev
    - libssl-doc

  - name: Install PostgreSQL 
    apt: name={{ item }} update_cache=true state=present
    with_items:
    - postgresql
    - postgresql-contrib
    - libpq-dev
    - python3-psycopg2

  - name: Ensure the PostgreSQL service is running
    service: name=postgresql state=started enabled=yes

  - name: Create the database specified in vars
    become: true
    become_user: postgres
    postgresql_db: name=postgres-test
        template='template0'
        state=present

  - name: Ensure user has access to the new database
    become: true
    become_user: postgres
    postgresql_user: db=postgres-test
        name=postgres
        password=postgres-test
        priv=ALL
        state=present

  - name: Ensure user does not have unnecessary permissions
    become: true
    become_user: postgres
    postgresql_user: name=postgres
       role_attr_flags=NOSUPERUSER,NOCREATEDB
       state=present

  - name: Add some dummy data to our database
    become: true
    become_user: postgres
    shell: psql postgres-test < /tmp/dump.sql
